alias gdiff='git diff -b'
alias gstatus='git status'
alias gfetch='git fetch'
alias gpush='git push'
alias gpforce='git push --force-with-lease'
alias gcommit='git commit -m'
alias gamend='git commit --amend --no-edit'
alias gaall='git add . --all'
alias gbra='git branch -a'
alias gad='git add --all'
alias gap='git add --all --patch'
alias gpull='git pull'
alias gcheck='git checkout'
alias gtre='git log --graph --abbrev-commit --decorate --date=relative --all'
alias glog='git log --pretty=format:"%C(auto)%h - %Creset%an, %C(green)%ar: %C(bold cyan)%s%Creset"'
alias gfiles='git diff-tree --no-commit-id --name-only -r'
alias gshow='git show'
alias gsearch='git log --'
alias gfind='git log -S'
alias gnotmerged='git branch --no-merged'
alias suvim='sudo vim'
